version: "2.1"

services:
  activemq:
    image: pandorasystems/activemq
    container_name: activemq
    ports:
      - "61616:61616"
      - "8181:8181"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://fcrepo:8080/fcrepo/rest"]
      interval: 45s
      timeout: 20s
      retries: 2

  fcrepo:
    image: pandorasystems/fcrepo:4.8.0
    container_name: fcrepo
    environment:
      CATALINA_OPTS: -Dfcrepo.home=/mnt/fcrepo-data -Dfcrepo.spring.configuration=file:/etc/spring/fcrepo-config.xml
    ports:
      - "8080:8080"
    depends_on:
      - activemq
    volumes:
      - fcrepo-volume:/mnt/fcrepo-data

  jmeter-master:
    image: pandorasystems/jmeter-master:0.0.1
    ports:
      - "60000"
    depends_on:
      activemq:
        condition: service_healthy
#    environment:
#     - JMETER_CMD=-Dfedora_4_context=fcrepo/rest -Dcontainer_threads=1 -n -t fedora-base.jmx

  jmeter-server:
    image: pandorasystems/jmeter-server
    ports:
      - "50000"
      - "1099"
    depends_on:
      activemq:
        condition: service_healthy

volumes:
  fcrepo-volume: